"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Navigation2, Clock, CheckCircle2 } from "lucide-react";
import { PageHeader, Card, Button, TextInput } from "@/components/ui";
import api from "@/lib/api";

const LOCATIONS = ["Gate A", "Gate B", "Gate C", "Gate D", "Gate E", "Gate F", "Gate G", "Metro Station Concourse", "Parking Lot 3"];
const DESTINATIONS = ["Seat Z1-114", "Seat Z4-208", "Nearest restroom", "Nearest first aid post", "Fan Zone Concourse", "Accessible Seating Platform"];

export default function NavigationPage() {
  const [from, setFrom] = useState("Gate C");
  const [to, setTo] = useState("Seat Z1-114");
  const [accessible, setAccessible] = useState(false);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<{ route_summary: string; steps: string[]; estimated_walk_minutes: number } | null>(null);

  const submit = async () => {
    setLoading(true);
    try {
      const res = await api.getRoute(from, to, accessible, "English");
      setResult(res);
    } catch {
      setResult(null);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div>
      <PageHeader
        eyebrow="Fan Experience"
        title="Smart Wayfinding"
        description="AI-generated, step-by-step directions between any two points inside the venue — accessible routing included."
      />

      <div className="grid gap-5 lg:grid-cols-[380px_1fr]">
        <Card className="flex flex-col gap-4">
          <label className="block">
            <span className="mb-1.5 block text-[13px] font-medium text-ink/70">Current location</span>
            <select value={from} onChange={(e) => setFrom(e.target.value)} className="focus-ring w-full rounded-lg border border-line bg-paper px-3.5 py-2.5 text-[14px] outline-none">
              {LOCATIONS.map((l) => <option key={l} value={l}>{l}</option>)}
            </select>
          </label>
          <label className="block">
            <span className="mb-1.5 block text-[13px] font-medium text-ink/70">Destination</span>
            <select value={to} onChange={(e) => setTo(e.target.value)} className="focus-ring w-full rounded-lg border border-line bg-paper px-3.5 py-2.5 text-[14px] outline-none">
              {DESTINATIONS.map((l) => <option key={l} value={l}>{l}</option>)}
            </select>
          </label>

          <label className="flex items-center gap-2.5 rounded-lg border border-line bg-paper px-3.5 py-3">
            <input
              type="checkbox"
              checked={accessible}
              onChange={(e) => setAccessible(e.target.checked)}
              className="h-4 w-4 accent-pitch"
            />
            <span className="text-[13.5px] text-ink/70">Require step-free / accessible route</span>
          </label>

          <Button onClick={submit} disabled={loading} className="mt-1 w-full">
            <Navigation2 size={16} /> {loading ? "Calculating route…" : "Get directions"}
          </Button>
        </Card>

        <Card className="min-h-[320px]">
          <AnimatePresence mode="wait">
            {result ? (
              <motion.div key="result" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} transition={{ duration: 0.3 }}>
                <div className="mb-5 flex items-center justify-between">
                  <p className="text-[15px] leading-relaxed text-ink/80">{result.route_summary}</p>
                  <div className="ml-4 flex shrink-0 items-center gap-1.5 rounded-full bg-pitch-soft px-3 py-1.5 text-[13px] font-semibold text-pitch-deep">
                    <Clock size={14} /> {result.estimated_walk_minutes} min
                  </div>
                </div>
                <ol className="space-y-3">
                  {result.steps.map((s, i) => (
                    <motion.li
                      key={i}
                      initial={{ opacity: 0, x: -6 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ duration: 0.25, delay: i * 0.08 }}
                      className="flex items-start gap-3 rounded-lg border border-line bg-paper px-4 py-3"
                    >
                      <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-ink text-[11px] font-semibold text-white">
                        {i + 1}
                      </span>
                      <span className="text-[13.5px] leading-relaxed text-ink/75">{s}</span>
                    </motion.li>
                  ))}
                </ol>
                <div className="mt-4 flex items-center gap-1.5 text-[12.5px] text-ink/62">
                  <CheckCircle2 size={14} /> Route generated by Gemini, grounded in venue gate and zone data.
                </div>
              </motion.div>
            ) : (
              <div className="flex h-full min-h-[280px] flex-col items-center justify-center text-center text-ink/62">
                <Navigation2 size={28} strokeWidth={1.5} className="mb-3" />
                <p className="text-[14px]">Choose a start and destination, then request directions.</p>
              </div>
            )}
          </AnimatePresence>
        </Card>
      </div>
    </div>
  );
}
